//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangTuKhai
    {
        public int IDTuKhai { get; set; }
        public string IDNhanVien { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
        public string NoiDung { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
