//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKhenThuong
    {
        public string IDHopDong { get; set; }
        public int IDKhenThuong { get; set; }
        public Nullable<System.DateTime> NgayQuyetDinh { get; set; }
        public string NoiDung { get; set; }
        public string QuyetDinhSo { get; set; }
        public int IDCTKT { get; set; }
    
        public virtual HoDongLaoDong HoDongLaoDong { get; set; }
        public virtual LoaiKhenThuong LoaiKhenThuong { get; set; }
    }
}
