//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoDongLaoDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoDongLaoDong()
        {
            this.ChiTietKhenThuongs = new HashSet<ChiTietKhenThuong>();
            this.ChiTietKiLuats = new HashSet<ChiTietKiLuat>();
            this.NhanVien_ChucVu = new HashSet<NhanVien_ChucVu>();
            this.NhanVien_PhongBan = new HashSet<NhanVien_PhongBan>();
        }
    
        public string IDHopDong { get; set; }
        public string IDNhanVien { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public Nullable<System.DateTime> NgayHieuLuc { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string QuyetDinhSo { get; set; }
        public string NoiDungTomTat { get; set; }
        public Nullable<int> IDLoaHopDong { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKhenThuong> ChiTietKhenThuongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKiLuat> ChiTietKiLuats { get; set; }
        public virtual LoaiHopDong LoaiHopDong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien_ChucVu> NhanVien_ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien_PhongBan> NhanVien_PhongBan { get; set; }
    }
}
