//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiKhenThuong
    {
        public LoaiKhenThuong()
        {
            this.ChiTietKhenThuongs = new HashSet<ChiTietKhenThuong>();
        }
    
        public int IDKhenThuong { get; set; }
        public string TenKhenThuong { get; set; }
        public string HinhThuc { get; set; }
    
        public virtual ICollection<ChiTietKhenThuong> ChiTietKhenThuongs { get; set; }
    }
}
