//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien_KyNang
    {
        public string IDNhanVien { get; set; }
        public int IDKyNang { get; set; }
        public Nullable<int> SoNamKinhNghiem { get; set; }
        public int IDNVKN { get; set; }
    
        public virtual KyNang KyNang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
