//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien_TrinhDo
    {
        public string IDNhanVien { get; set; }
        public int IDTrinhDo { get; set; }
        public Nullable<System.DateTime> NamTotNghiep { get; set; }
        public string NoiDaoTao { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public string XepLoai { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual TrinhDoHocVan TrinhDoHocVan { get; set; }
    }
}
