//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongBan
    {
        public PhongBan()
        {
            this.NhanVien_PhongBan = new HashSet<NhanVien_PhongBan>();
        }
    
        public int IDPhongBan { get; set; }
        public string TenPhongBan { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<NhanVien_PhongBan> NhanVien_PhongBan { get; set; }
    }
}
