//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLNS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNSDataEntities : DbContext
    {
        public QLNSDataEntities()
            : base("name=QLNSDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangTuKhai> BangTuKhais { get; set; }
        public virtual DbSet<ChiTietKhenThuong> ChiTietKhenThuongs { get; set; }
        public virtual DbSet<ChiTietKiLuat> ChiTietKiLuats { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<HoDongLaoDong> HoDongLaoDongs { get; set; }
        public virtual DbSet<KyNang> KyNangs { get; set; }
        public virtual DbSet<LoaiHopDong> LoaiHopDongs { get; set; }
        public virtual DbSet<LoaiKhenThuong> LoaiKhenThuongs { get; set; }
        public virtual DbSet<LoaiKiLuat> LoaiKiLuats { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhanVien_ChucVu> NhanVien_ChucVu { get; set; }
        public virtual DbSet<NhanVien_KyNang> NhanVien_KyNang { get; set; }
        public virtual DbSet<NhanVien_PhongBan> NhanVien_PhongBan { get; set; }
        public virtual DbSet<NhanVien_TrinhDo> NhanVien_TrinhDo { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<TrinhDoHocVan> TrinhDoHocVans { get; set; }
        public virtual DbSet<DangNhap> DangNhaps { get; set; }
    }
}
