//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrinhDoHocVan
    {
        public TrinhDoHocVan()
        {
            this.NhanVien_TrinhDo = new HashSet<NhanVien_TrinhDo>();
        }
    
        public int IDTrinhDo { get; set; }
        public string TenTrinhDo { get; set; }
    
        public virtual ICollection<NhanVien_TrinhDo> NhanVien_TrinhDo { get; set; }
    }
}
